name: Build Blog

on:
  push:
    paths:
      - 'posts/**'
      - 'convert.py'
      - 'template/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Build HTML
        run: python convert.py

      - name: Push to repo
        run: |
            git config user.name "Daradege"
            git config user.email "darg.q.a.a@gmail.com"
            git remote set-url origin https://x-access-token:${{ secrets.PERSONAL_TOKEN }}@github.com/Daradege/staticblog.git
            git remote -v
            git add site
            git commit -m "Update blog site" || echo "Nothing to commit"
            git push origin main
